# Generated by Django 4.1.7 on 2023-02-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('achievment', models.CharField(max_length=150)),
            ],
        ),
    ]
