# Generated by Django 4.1.7 on 2023-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('week_goal', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
