# Generated by Django 4.1.7 on 2023-02-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0002_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('event_title', models.CharField(max_length=150)),
                ('event_description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='description',
            new_name='meeting_description',
        ),
    ]
